name=input("enter your name:")
amount=float(input("Enter amount in inr:"))
currency=input("enter currency name:")
exchange_rate=float(input("Enter exchange rate:"))
converted_amount =amount*exchange_rate
print("="*30)
print("      currency converter")
print("="*30)
print(f"Name             : {name}")
print(f"Amount(INR)      : {amount}")
print(f"currency         : {currency}")
print(f"Exchange rate    : {exchange_rate}")
print()
print(f"Converted Amount : {converted_amount:.2f}{currency}")